config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  
  devise_for :users
    resources :products do 
      resources :delivery_details      
  end
  
  resources :profiles 
  resources :addresses
  
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show] # Ensure user is logged in for specific actions
  before_action :set_profile, only: [ :edit, :update]

  def index
    @profiles = Profile.all
  end

  def new
    @profile = current_user.build_profile
  end

  def create
    @profile = current_user.build_profile(profile_params) # Correct method for a `has_one` association

    if @profile.save
      redirect_to profile_path(@profile), notice: 'Profile created successfully.'
    else
      render :new
    end
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    # Ensure `@profile` is set by `set_profile`
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'Profile updated successfully.'
    else
      render :edit
    end
  end

  # def destroy
  #   # Ensure `@profile` is set by `set_profile`
  #   @profile.destroy
  #   redirect_to profiles_path, notice: 'Profile deleted successfully.'
  # end

  private

  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:name, :contact_no, :age, :gender)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with model: @profile do |form| %>

<div>
  <%= form.label :name %><br>
  <%= form.text_field :name %>
</div>

<div>
  <%= form.label :contact_no %><br>
  <%= form.text_field :contact_no %>
</div>

<div>
  <%= form.label :age %><br>
  <%= form.text_field :age %>
</div>

<div>
  <%= form.label :gender %><br>
  <%= form.text_field :gender %>
</div>  

<div>
  <%= form.submit "create profile" %>
</div>

<% end %>
<%= link_to "show", profile_path(@profile) if @profile.persisted? %>

<%= link_to "cancel ", root_path %>

app/views/profiles/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form' %>

app/views/profiles/index.html.erb
<h3>Profiles</h3>

<% @profiles.each do |profile| %>
  <h1><%= profile.name %></h1>

  <%= link_to "Edit Profile", edit_profile_path(profile.id) %> |
<% end %>

<%= link_to 'New Profile', new_profile_path %> |

<%= link_to "Back to product", products_path %>

app/views/profiles/new.html.erb
<h1> Profile </h1>


<%= render 'form' %>

app/views/profiles/show.html.erb
<h1>Profile Details</h1>

<p>Name: <%= @profile.name %></p>
<p>Contact No: <%= @profile.contact_no %></p>
<p>Age: <%= @profile.age %></p>
<p>Gender: <%= @profile.gender %></p>

<div class="actions">

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Delete', profile_path(@profile), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', root_path %>
</div>