config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  
  devise_for :users
    resources :products do 
      resources :delivery_details      
  end
  
  resources :profiles 
  resources :addresses
  
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
 before_action :set_address, only: [:show, :edit, :update, :destroy]

def new
	@address = Address.new
end

def index
	@addresses = current_user.addresses

	#@address = current_user.address #(for one-to-to relation)
  #@address = Address.find_by(user_id: params[:user_id]) # or however you're querying


end

def create
	@address = current_user.addresses.new(address_params)
	
	if @address.save
		redirect_to addresses_path, notice: 'Address added successfully.'
	else
		render :new
	end
end

def edit 
	#@address = current_user.address
end

def update
	# if current_user.address.update(address_params)
	# 	redirect_to root_path, notice: 'Address update successfully.'
	# else
	# 	render.edit
	# end
	 if @address.update(address_params)
      redirect_to addresses_path, notice: 'Address updated successfully.'
   else
      render :edit
   end
end

# def destroy
# 	@address.destroy
# 	redirect_to addresses_path, notice: "addresses deleted successfully!"

# end
def destroy
  @address = Address.find(params[:id]) # Ensure @address is correctly set
  @address.destroy
  redirect_to addresses_path, notice: "Address deleted successfully!"
end


 private

 def set_address
    @address = Address.find_by(id: params[:id])
    if @address.nil?
      redirect_to addresses_path, alert: 'Address not found.'
    end
  end

  def address_params
    params.require(:address).permit(:colony, :city, :pincode, :country)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/edit.html.erb
<h1> Edit </h1>

<%# <%= form_with model: address do |form| %> 
  
<%# <%= form_with model: @address, url: address_path, method: :patch do |f| %>
  

<%# <%= render "form", address: @address %> 



<%= form_with model: @address do |form| %>

<div>
	<%= form.label :colony %><br>
	<%= form.text_field :colony %>
</div>

<div>
	<%= form.label :city %><br>
	<%= form.text_field :city %>
</div>

<div>
	<%= form.label :pincode %><br>
	<%= form.text_field :pincode %>
</div>

<div>
	<%= form.label :country %><br>
	<%= form.text_field :country %>
</div>	

<div>
	<%= form.submit "update address" %>
</div>

<% end %>

app/views/addresses/index.html.erb
<% if @addresses.present? %>
  <ul>
    <% @addresses.each do |address| %>
      <li>
        <%= address.colony %>, <%= address.city %>, <%= address.country %>, <%= address.pincode %>
        <%# <%= link_to 'Add address', address_path(address) %>
        <%= button_to 'Edit', edit_address_path(address) %>
        <%= button_to 'Delete', address_path(address), method: :delete, data: { turbo: false, confirm: 'Are you sure?' } %>

      </li>
    <% end %>
  </ul>
<% else %>
  <p>No addresses added yet.</p>
<% end %>

app/views/addresses/new.html.erb
<h1> Address </h1>

<%= form_with model: @address do |form| %>

<div>
	<%= form.label :colony %><br>
	<%= form.text_field :colony %>
</div>

<div>
	<%= form.label :city %><br>
	<%= form.text_field :city %>
</div>

<div>
	<%= form.label :pincode %><br>
	<%= form.text_field :pincode %>
</div>

<div>
	<%= form.label :country %><br>
	<%= form.text_field :country %>
</div>	

<div>
	<%= form.submit "save address" %>
</div>

<% end %>

app/views/addresses/show.html.erb
<p><%= @address.colony %></p>

<p><%= @address.city %></p>

<p><%= @address.pincode %></p>

<p><%= @address.country %></p>
 


<%# <%# <ul>
  <li><%= link_to "Edit", edit_address_path(@address) %><%# </li>
</ul>  %>