config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  
  devise_for :users
    resources :products do 
      resources :delivery_details      
  end
  
  resources :profiles 
  resources :addresses
  
end

app/models/delivery_detail.rb
class DeliveryDetail < ApplicationRecord

	belongs_to :product

	validates :date, presence: true
end

app/controllers/delivery_details_controller.rb
class DeliveryDetailsController < ApplicationController
  before_action :set_product, only: [:new, :create, :index]
  before_action :set_delivery_detail, only: [:show, :edit, :update, :destroy]

  
 def index
  @product = Product.find(params[:product_id])
  @delivery_details = @product.delivery_details
 end

  def show
  end

  def new
    @delivery_detail = @product.delivery_details.new
  end

  
  def create
    @delivery_detail = @product.delivery_details.new(delivery_detail_params)
    if @delivery_detail.save
      redirect_to product_delivery_details_path(@product), notice: "Delivery detail created successfully."
    else
      render :new
    end
  end

 def edit
  @product = Product.find(params[:product_id])
  @delivery_detail = @product.delivery_details.find(params[:id])
 end


  def update
  if @delivery_detail.update(delivery_detail_params)

    redirect_to product_delivery_detail_path(@product, @delivery_detail), notice: "Delivery detail updated successfully."
  else
    render :edit
  end
end


  def destroy
    @delivery_detail.destroy
    redirect_to product_delivery_details_path(@delivery_detail.product), notice: "Delivery detail deleted successfully."
  end

  private

 def set_product
  @product = Product.find_by(id: params[:product_id])
  redirect_to products_path, alert: "Product not found" if @product.nil?
end



def set_delivery_detail
  @product = Product.find_by(id: params[:product_id])
  
  if @product
    @delivery_detail = @product.delivery_details.find_by(id: params[:id])
    
    unless @delivery_detail
      redirect_to products_path, alert: "Delivery Detail not found" and return
    end
  else
    redirect_to products_path, alert: "Product not found" and return
  end
end




  # Permit delivery detail parameters
  def delivery_detail_params
    params.require(:delivery_detail).permit(:date, :product_id)
  end
end

app/helpers/delivery_details_helper.rb
module DeliveryDetailsHelper
end

app/views/delivery_details/_form.html.erb
<%= form_with(model: [@product, @delivery_detail], local: true) do |form| %>
  <div>
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>
  <%= form.hidden_field :product_id, value: @product.id %>
  <div>
    <%= form.submit "Create Delivery Detail" %>
  </div>
<% end %>

app/views/delivery_details/edit.html.erb
<h1>Edit Delivery Detail</h1>

<%= render "form", delivery_detail: @delivery_detail %>

<%= link_to "Back", product_delivery_details_path(@product) %>

app/views/delivery_details/index.html.erb
<h1>Delivery Details</h1>

<button><%= link_to "New Delivery Detail", new_product_delivery_detail_path(@product) %></button>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @delivery_details.each do |detail| %>
      <tr>
        <td><%= detail.date %></td>
        <td>
         <button><%= link_to 'Edit', edit_product_delivery_detail_path(@product, detail) %></button>
          <%= button_to 'Delete', product_delivery_detail_path(@product, detail), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/delivery_details/new.html.erb
<h1>New Delivery Detail</h1>

<%= render "form", delivery_detail: @delivery_detail %>

<%= link_to "Back", product_delivery_details_path(@product) %>

app/views/delivery_details/show.html.erb
<h1>Delivery Detail</h1>
<p>Date:<%= @delivery_detail.date %></p>
<p>Product:<%= @delivery_detail.product.name if @delivery_detail.product %></p>

<%= link_to "Edit", edit_product_delivery_detail_path(@delivery_detail.product, @delivery_detail) %> |
<%= link_to "Back", product_delivery_details_path(@delivery_detail.product) %>