config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  
  devise_for :users
    resources :products do 
      resources :delivery_details      
  end
  
  resources :profiles 
  resources :addresses
  
end

app/models/product.rb
class Product < ApplicationRecord

	has_many :delivery_details 

	validates :name, :price, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

	def index
	    @products = Product.all
	end

	def new 
		@product = Product.new
	end

	def create
		 @product = Product.new(product_params)

		 if @product.save
		 	redirect_to products_path, notice: 'Product created successfully.'
		 else 
		 	render :new
		 end
	end

	def show
  @product = Product.find_by(id: params[:id])
  unless @product
    redirect_to products_path, alert: "Product not found"
  end
end


	def edit
  @product = Product.find(params[:id])
end


	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			redirect_to products_path, notice: 'Product update successfully.'
		else
			render :edit
		end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path, notice: 'Product deleted successfully.'
	end

	end

	private 

	def product_params
        params.require(:product).permit(:name, :price)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with model: @product, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>Products</h1>


  <table>
    <thead>
      <tr>
        <th>Product Name</th>
        <th>Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td><%= link_to 'Show', product_path(product) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


<button><%= link_to "Add Product", new_product_path %></button><br>


<button><%= link_to "Show Profile", profiles_path(current_user) %></button>

<button><%= link_to "Addresses", new_address_path %></button>

<button><%= link_to "Add delivery_detail", new_product_delivery_detail_path(@products.first) %></button>

<p><%= button_to "Logout", destroy_user_session_path, method: :delete, data: { no_turbolink: true } %></p>

app/views/products/new.html.erb
<h1>Product</h1>
<%= form_with model: @product, local: true do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :price %>
  <%= f.number_field :price %><br>

  <%= f.submit "Save Product" %>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p><%= @product.price %></p>

<ul>
	<li><%= link_to "edit", edit_product_path(@product) %></li>
	<li><%= link_to "Destroy", product_path(@product), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>